services:
    tawktoosfu:
        image: sanketsmane/kidokool:latest
        build: .
        container_name: tawktoosfu
        hostname: tawktoosfu
        restart: unless-stopped
        env_file: .env
        network_mode: 'host'
        volumes:
            - ./app/src/config.js:/src/app/src/config.js:ro
            - ./.env:/src/.env:ro
            # Mandatory volume if `RECORDING_ENABLED=true` in the .env
            # - ./app/rec:/src/app/rec
            # Mandatory volume if `RTMP_FROM_FILE=true` in the .env
            # - ./app/rtmp:/src/app/rtmp
