services:
    kidokool-rtmp:
        container_name: kidokool-rtmp
        #image: tiangolo/nginx-rtmp
        image: kidokool/rtmp:latest
        volumes:
            - ./nginx.conf/:/etc/nginx/nginx.conf/:ro
            - ./stat.xsl/:/usr/share/nginx/html/stat.xsl/:ro
        ports:
            - '1935:1935'
            - '8081:8081'
        restart: unless-stopped
